#!/usr/bin/env bash

set -o nounset -o errexit -o pipefail
unset CDPATH

url="http://127.0.0.1:4000"

root_dir=$(cd "$(dirname "$0")" && pwd)
command_name=$root_dir/$(basename "$0")

fail () {
    printf "%s: Error: %s\n" "$command_name" "$*" >&2
    exit 1
}


if (( $# == 0 ))
then fail no args
else case $1 in
         serve )
             cd "$root_dir"
             bundle exec jekyll serve --incremental
             ;;
         build )
             cd "$root_dir"
             rm -rf "$HOME"/tmp/site
             bundle exec jekyll build --verbose --destination "$HOME"/tmp/site
             ;;
         valid )
             if ! curl --silent --output /dev/null "$url" 
                then printf 'Nothing running at %s\n' "$url" >&2
                     exit 1
             fi
             wget --span-hosts --no-config --no-verbose --spider --recursive --page-requisites "$url"
             ;;
         valid-page )
             wget --span-hosts --no-config --no-verbose --spider --page-requisites "$url/json/overview"
             ;;
         * ) fail Unknown command: "$1";;
                
     esac
fi
