#!/usr/bin/env bash

# Check local site for missing links & log them out.
# Created 2017-06-19 webb.roberts@gtri.gatech.edu

temporary_dir=$(mktemp --directory)
remove_temporary_dir () {
  rm -rf "$temporary_dir"
}
trap remove_temporary_dir 0

cd "$temporary_dir"

wget --spider --recursive http://127.0.0.1:4000

